server:
    port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://sql12.freemysqlhosting.net:3306/test?useSSL=false&jdbcCompliantTruncation=false&characterEncoding=UTF-8&allowMultiQueries=true
    username: sql12236335
    password: RzfhzjUgRD
    driver-class-name: com.mysql.jdbc.Driver
  hikari:
    maxLifetime: 1765000
    maximumPoolSize: 15

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: ren.ascence.entity
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

debug: false
logging:
  config: classpath:config/logback-prod.xml
  
 
